name: release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup java
              uses: actions/setup-java@v5
              with:
                  distribution: 'jetbrains'
                  java-version: '21'

            - name: Build
              run: |
                  chmod +x ./gradlew
                  ./gradlew assembleRelease

            - name: Sign
              id: sign
              uses: ilharp/sign-android-release@v2
              with:
                  signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
                  keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
                  keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                  keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

            - name: Read version
              id: read_version
              run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

            - name: Read changelog
              id: read_changelog
              uses: mindsers/changelog-reader-action@v2
              with:
                  version: ${{ steps.read_version.outputs.version }}

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  draft: false
                  files: ${{steps.sign.outputs.signedFile}}
                  body: |
                      ## ${{ steps.read_changelog.outputs.version }} - ${{ steps.read_changelog.outputs.date }}  

                      ${{ steps.read_changelog.outputs.changes }}
